# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Alison Gardner
tagline:          'Academic researcher and independent consultant'
description:      'Assistant Professor of Local Governance and Antislavery Policy with extensive experience in local governance and public policy.'
url:              http://alisongardner.me.uk
baseurl:          /
port: 			  4101

email:			  AlisonGardner12@gmail.com
twitter_username: AlisonGardner12
linkedin:		  https://uk.linkedin.com/in/alison-gardner-b0739426
profilepicurl:	  alison.jpg

author:
  name:           'Alison Gardner'
  url:            http://alisongardner.me.uk/

# Custom vars
